package com.common;

import java.io.Serializable;

public enum Action implements Serializable {
    SIGNIN, SIGNUP, CHANGEPASSWORD, EDITCLIENTINFO, EDITLOGININFO, CREATESIMPLECARD, CREATEMULTICARD, MAKEPRIORITYCARD, DEACTIVATECARD, DELETECARD, MAKEPRIORITYMCARD, DEACTIVATEMCARD, DELETEMCARD, TRANSFERCARD
}
